### ISSUE TITLE
Does not compile on 0.11.14

### ISSUE THREAD

**Issue by marcominetti** [audreyt/node-webworker-threads#35]
node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/marco.minetti/Desktop/test/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:6:0:
/home/marco.minetti/.node-gyp/0.11.14/src/node.h:377:43: error: overloaded function with no contextual type information
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/marco.minetti/.node-gyp/0.11.14/src/node.h:408:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)
   ^
../src/WebWorkerThreads.cc:971:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(WebWorkerThreads, Init)
 ^
make: **\* [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
